// Respectful, celebratory facts shown on the reveal screen.
// hello = a greeting in the language; speakers ≈ first+second language; note = a warm fact.
export const FACTS = {
  eng: { hello: "Hello", speakers: "~1.5 billion", note: "A Germanic language now spoken on every continent — and the world's most common second language." },
  fra: { hello: "Bonjour", speakers: "~300 million", note: "Spoken across five continents — from Québec to Senegal to the South Pacific." },
  deu: { hello: "Hallo", speakers: "~135 million", note: "Famous for building long, precise compound words from smaller ones." },
  spa: { hello: "Hola", speakers: "~560 million", note: "The world's second-most-spoken native language, anchored across the Americas and Spain." },
  ita: { hello: "Ciao", speakers: "~65 million", note: "The direct descendant of Latin, and the language of opera." },
  por: { hello: "Olá", speakers: "~260 million", note: "Carried from Portugal to Brazil, Angola, Mozambique and beyond." },
  nld: { hello: "Hallo", speakers: "~25 million", note: "Close cousin to both English and German, spoken in the Netherlands and Flanders." },
  cat: { hello: "Hola", speakers: "~10 million", note: "A proud Romance language of Catalonia, Valencia and the Balearic Islands." },
  eus: { hello: "Kaixo", speakers: "~750 thousand", note: "Basque is a language isolate — unrelated to any other on Earth, older than the Indo-European languages around it." },
  gle: { hello: "Dia duit", speakers: "~1.8 million", note: "A Celtic language and the first official language of Ireland." },
  swe: { hello: "Hej", speakers: "~10 million", note: "A melodic, pitch-accented language of Sweden and parts of Finland." },
  nor: { hello: "Hei", speakers: "~5 million", note: "Norwegian's many dialects are all widely understood — there's no single 'standard' spoken form." },
  dan: { hello: "Hej", speakers: "~6 million", note: "Known for its soft consonants and the famously tricky 'stød' catch in the voice." },
  fin: { hello: "Moi", speakers: "~5 million", note: "Uralic, not Nordic — a distant relative of Estonian and Hungarian." },
  isl: { hello: "Halló", speakers: "~350 thousand", note: "So conservative that Icelanders can still read medieval Norse sagas." },
  rus: { hello: "Привет — Privet", speakers: "~255 million", note: "The most widely spoken native language in Europe, written in Cyrillic." },
  pol: { hello: "Cześć", speakers: "~45 million", note: "A West Slavic language celebrated (and feared) for its consonant clusters." },
  ukr: { hello: "Привіт — Pryvit", speakers: "~40 million", note: "An East Slavic language known for its musical, vowel-rich sound." },
  ces: { hello: "Ahoj", speakers: "~11 million", note: "Czech's friendly 'Ahoj' actually comes from sailors — though the country is landlocked." },
  ron: { hello: "Salut", speakers: "~24 million", note: "A Romance language flourishing in a sea of Slavic neighbors." },
  hun: { hello: "Szia", speakers: "~13 million", note: "Uralic and unrelated to its neighbors — it builds meaning by stacking endings onto words." },
  bul: { hello: "Здравей — Zdravey", speakers: "~8 million", note: "The first language ever written in the Cyrillic alphabet." },
  srp: { hello: "Здраво — Zdravo", speakers: "~9 million", note: "One of the few languages written fluently in two alphabets — Cyrillic and Latin." },
  tur: { hello: "Merhaba", speakers: "~85 million", note: "Turkic and beautifully regular, with vowels that harmonize across each word." },
  ara: { hello: "مرحبا — Marḥaban", speakers: "~400 million", note: "A single written standard unites dozens of rich spoken varieties across the Arab world." },
  heb: { hello: "שלום — Shalom", speakers: "~9 million", note: "An ancient language revived into everyday speech a little over a century ago." },
  fas: { hello: "سلام — Salâm", speakers: "~130 million", note: "Persian — the language of the poets Rumi and Hafez." },
  cmn: { hello: "你好 — Nǐ hǎo", speakers: "~920 million", note: "The most spoken native language on Earth; meaning rides on four tones." },
  jpn: { hello: "こんにちは — Konnichiwa", speakers: "~125 million", note: "Written with three scripts at once: kanji, hiragana and katakana." },
  kor: { hello: "안녕하세요 — Annyeonghaseyo", speakers: "~80 million", note: "Hangul was designed in 1443 to be so logical that anyone could learn it." },
  vie: { hello: "Xin chào", speakers: "~85 million", note: "A tonal language of six tones, written in a Latin-based alphabet." },
  tha: { hello: "สวัสดี — Sawasdee", speakers: "~60 million", note: "Five tones and its own graceful, curving script." },
  ind: { hello: "Halo", speakers: "~200 million", note: "The unifying language of more than 17,000 islands." },
  hin: { hello: "नमस्ते — Namaste", speakers: "~600 million", note: "Written in the Devanagari script, where a line runs along the top of the words." },
  tam: { hello: "வணக்கம் — Vaṇakkam", speakers: "~85 million", note: "One of the world's oldest living classical languages, with a 2,000-year literary tradition." },
  ben: { hello: "নমস্কার — Nomoshkar", speakers: "~270 million", note: "The language of the poet Tagore, and the reason World Mother Language Day exists." },
  yor: { hello: "Báwo", speakers: "~45 million", note: "A tonal West African language rich with proverbs and praise poetry." },
  amh: { hello: "ሰላም — Selam", speakers: "~35 million", note: "Written in the elegant Geʽez script — one of Africa's own writing systems." },
};

export const fallbackFact = { hello: "Hello", speakers: "millions of", note: "One of the thousands of living languages that make up the human chorus." };
